version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: LocalPassword
  backend:
    build: .
    command: python3 manage.py test
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
